services:
  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: pk-postgres02
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: pk_database
    ports:
      - "5432:5432"    
    # volumes:
    #  - pgdata:/var/lib/postgresql/data
    # networks:
    #   - app-network

  backend:
    build:
      context: .
      dockerfile: ./node_backend/Dockerfile
    container_name: pk-backend
    ports:
      # 8081:8081
     - "1337:1337"
    # networks:
    #   - app-network

  # frontend:
  #   build:
  #     context: ./frontend
  #     dockerfile: Dockerfile
  #   ports:
  #    - "5000:5000" # ???
  #   # networks:
  #   #   - app-network
  #   environment:
  #     - name=value



  # networks:
    # - app-network

  # volumes:
  #     pgdata:









