services:
  db:
    build:
      context: .
      dockerfile: ./database/Dockerfile
    container_name: pk-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: pk_database
    ports:
      - "5432:5432"

  backend:
    build:
      context: .
      dockerfile: ./node_backend/Dockerfile
    container_name: pk-backend
    ports:
     - "1337:1337"